# LLM Test Bench Configuration
# API keys loaded from .env file

# Provider configurations
providers:
  - name: "bedrock_claude"
    model: "anthropic.claude-3-haiku-20240307-v1:0"
  - name: "openai"
    model: "gpt-4.1-nano-2025-04-14"
  - name: "gemini"
    model: "gemini-2.0-flash-lite"

# Test execution settings
delay_between_calls: 1
delay_between_test_cases: 2

# Test cases
test_cases:
  - name: "Image Analysis"
    prompt: "Describe what you see in this image in detail."
    image_path: "test_images/Radioheadokcomputer.png"
    max_tokens: 2000
    temperature: 0.7
